# Generated by Django 4.1 on 2023-01-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(to="core.tag"),
        ),
    ]
